### ISSUE TITLE
Quantum Espresso fails to converge for common test

### ISSUE THREAD

**Issue by mszpindler** [Lumi-supercomputer/LUMI-EasyBuild-contrib#28]
This commonly used `ausurf` 
https://github.com/QEF/q-e/blob/develop/test-suite/benchmarks/pw/ausurf.in
test fails to converge with https://github.com/Lumi-supercomputer/LUMI-EasyBuild-contrib/blob/main/easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-cpeGNU-21.12.eb recipe

**Comment by egplar** [comment]
I think this is not a real issue. The ausurf test is set by default (as downloaded) to run only 2 SCF iterations, so it will not converge by design.

**Comment by mszpindler** [comment]
Thanks. I just wondered why they check for `convergence has been achieved` string in the output as an assertion if this case never converges.
